### PR TITLE
Update to latest version

### PR DESCRIPTION
**Pull request by strangemk2**
- unrar
- deadbeef api

### CODE REVIEW

**Comment by Alexey-Yakovenko** [comment]
@shaohao Hi, are you still updating this project?

**Comment by shaohao** [comment]
> @shaohao Hi, are you still updating this project?

 I have not used deadbeef for a long time. No more update for this plugin. But I will do some pull request merging if someone else like to update it.

**Comment by Alexey-Yakovenko** [comment]
@shaohao

Would you consider giving me permissions to update this repository then?
Or perhaps moving it under the Deadbeef-Player organization?

**Comment by shaohao** [comment]
> @shaohao
> 
> Would you consider giving me permissions to update this repository then?
> Or perhaps moving it under the Deadbeef-Player organization?

I just transfer this repository to you.
 Good Luck

**Comment by Alexey-Yakovenko** [comment]
Thanks!

**Pull request merged**
